# ref config: https://github.com/luizdepra/hugo-coder/blob/main/exampleSite/config.toml
baseURL = "https://www.rmachuca.me/"
title = "rmachuca.me"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 10
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
canonifyurls = true
disqusShortname = "rmachuca"

[params]
  author = "Rodrigo Machuca"
  description = "Rodrigo Machuca Personal Website"
  keywords = "blog,developer,swe,sysadmin,projects"
  info = "Software Engineer @Google"
  avatarURL = "images/profile.jpg"
  dateFormat = "January 2, 2006"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"
  since = 2020
  # Git Commit in Footer, uncomment the line below to enable it
  # commit = "https://github.com/rmachuca89/rmachuca.me/tree/"
  # Right To Left, shift content direction for languagues such as Arabic
  rtl = false
  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme = "auto"
  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle = false
  # Series see also post count
  maxSeeAlsoItems = 5
  # custom_css = ["css/custom.css"]
  # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  # customSCSS = []
  # custom_js = []
  hidefooter = false
  footercontent = "This site expresses only my personal opinion."
  hidecredits = false
  hidecopyright = false
  # Toggle MathJax Module and add JS into your site
  math = false
  [params.googleTagManager]
    id = "G-KVRHKRL0TL"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "github"
  url = "https://github.com/rmachuca89"
  icon = "fab fa-github fa-2x"
  weight = 1
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/rmachuca89"
  icon = "fab fa-twitter fa-2x"
  weight = 2
[[params.social]]
  name = "linkedIn"
  icon = "fab fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/rmachuca89/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "/about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "/posts/"
# TODO(#2): Add portfolio section
# [[menu.main]]
#   name = "Projects"
#   weight = 3
#   url  = "/projects/"

# TODO(#3): Add Spanish articles once I enable the i18n
