#+TITLE: Site Content
#+AUTHOR: Rodrigo Machuca
#+DESCRIPTION: org-mode markup content to be parsed and rendered into CommonMarkdown by ox-hugo
#+STARTUP: overview
#+HUGO_BASE_DIR: .
#+HUGO_SECTION: posts
* Blog Posts
** DONE Motivation and Blog Content Focus
CLOSED: [2020-09-04 Fri 21:46]
:PROPERTIES:
:ID:       c9eea857-3413-45d7-9281-3c4f5236857e
:EXPORT_FILE_NAME: motivation-and-blog-content-focus
:EXPORT_DATE: 2020-09-04
:END:

Howdy! you curious, smart and inquisitive internaut. This is my first post to
discuss my personal motivation on creating this space for you and me.

But first of all, *who am I* and why you should spend your valuable time surfing
through my content? I am just another geeky regular joe that enjoys tinkering
with new technologies and sharing it with the communities that has given me a
lot with no expected retribution or deferred payments. I am talking about the
/Linux and Free Open Source Software (FOSS)/ movements. For a more thorough view
of my personal interests and trajectory, please refer to [[https://www.rmachuca.me/about][my About]] section.

*What took me so long?* I had this personal project pending under my backlog of
wish lists and dream-line for a long time that I kept procrastinating. But times
have changed, COVID-19 is here to stay for a while, and so working from home
(WFH), which in turn has given me an unique opportunity of reclaiming that
scarce commute time back to work-out, learn, be with my lovely wife and of
course, play some video games.

*Why?* It is time to give back to the same communities that helped me grow,
learn and continue improving in my career. In addition, personally I want to
refine my communications skills (English, writing) and what better way than
jumping into the unknown of this bast cyberspace. Finally, I intend to use also
this resource for personal technical reference.

*** Focus

I will be focusing in the beginning on the following areas or technologies:

- Text Editing and Writing :: emacs, doom-emacs, org-mode, hugo
- Web Technologies :: HTML, CSS, Browsers, APIs (REST, GraphQL, Protobuf)
- Programming :: Python, JavaScript, Go
- Infrastructure :: Cloud (AWS, GCP), Networking
- DevOps and SRE Practices :: Monitoring, CI/CD, Automation and Integration

If time and motivation keeps going, I will expand the content to Spanish (my
native language) once I learn about [[https://gohugo.io/content-management/multilingual/][Hugo internationalization (i18n)]].
